/**
 * chunker.ts — Intelligent markdown chunking for Axon RAG
 *
 * Pure function module, zero network/DB dependencies.
 * Receives markdown text, returns an array of semantically coherent chunks
 * optimised for embedding + vector retrieval.
 *
 * Algorithm: Recursive Character Splitting
 *   1. Split by "\n## " (h2 headings) → sections
 *   2. If section > maxChunkSize → split by "\n### " (h3)
 *   3. If still large → split by "\n\n" (paragraphs)
 *   4. If still large → split by ". " (sentences)
 *   5. If still large → split by " " (words) — last resort
 *   6. Merge chunks < minChunkSize with the next chunk
 *   7. Add overlap: last N chars of previous chunk prepended to next
 *
 * Quality guarantees:
 *   - Never cuts mid-sentence (sentence boundary is a separator level)
 *   - Preserves markdown headers in the first chunk of each section
 *   - Overlap ensures retrieval context continuity across boundaries
 *   - Tracks which splitting strategy was used per chunk
 *
 * Known limitations:
 *   - Overlap characters are ADDED on top of chunk content, so the final
 *     char_count may exceed maxChunkSize by up to ~overlapSize + 5 chars.
 *     This is standard behaviour (same as LangChain's RecursiveCharacterTextSplitter).
 *   - Markdown code blocks containing "## " could cause incorrect splits.
 *     This is acceptable for Axon because summaries are generated by Gemini,
 *     not user-authored code with header-like comments.
 *
 * Fase 5 — Issue #30
 */

// ─── Public Types ───────────────────────────────────────────────────

export interface ChunkResult {
  /** Text content of the chunk (may include overlap prefix from previous chunk) */
  content: string;
  /** Sequential position (0-based) */
  order_index: number;
  /** Character count of content (includes overlap if present) */
  char_count: number;
  /** Splitting strategy that produced this chunk */
  strategy: "recursive" | "semantic";
}

export interface ChunkOptions {
  /** Maximum chars per chunk before splitting (default: 800) */
  maxChunkSize?: number;
  /**
   * Minimum chars per chunk — smaller ones get merged (default: 100).
   * Clamped to maxChunkSize if larger.
   */
  minChunkSize?: number;
  /**
   * Chars of overlap between consecutive chunks (default: 50).
   * Clamped to maxChunkSize / 4 if larger.
   * Note: overlap is ADDED to chunk content, so final char_count may
   * exceed maxChunkSize by approximately this amount.
   */
  overlapSize?: number;
}

const DEFAULTS = {
  maxChunkSize: 800,
  minChunkSize: 100,
  overlapSize: 50,
} as const;

// ─── Separator Hierarchy ────────────────────────────────────────────
//
// Ordered from coarsest (structural) to finest (character-level).
// Each level preserves more semantic coherence than the next.

const SEPARATORS = [
  "\n## ",   // H2 headings — major topic boundaries
  "\n### ",  // H3 headings — sub-topic boundaries
  "\n\n",    // Paragraph breaks
  ". ",      // Sentence boundaries
  " ",       // Word boundaries — last resort
] as const;

/** Check if a separator is a markdown header marker */
function isHeaderSeparator(sep: string): boolean {
  return sep.includes("#");
}

// ─── Entry Point ────────────────────────────────────────────────────

/**
 * Split markdown text into semantically coherent chunks for RAG embedding.
 *
 * @param text      Raw markdown content (typically summary title + content_markdown)
 * @param options   Override default chunk size / overlap parameters
 * @returns         Array of ChunkResult sorted by order_index
 *
 * @example
 *   const chunks = chunkMarkdown(summary.content_markdown);
 *   // → [{ content: "## Mitosis\n...", order_index: 0, char_count: 480, strategy: "recursive" }, ...]
 */
export function chunkMarkdown(
  text: string,
  options?: ChunkOptions,
): ChunkResult[] {
  // ── Guard: empty / whitespace-only input ──
  if (!text || text.trim().length === 0) return [];

  const raw = { ...DEFAULTS, ...options };

  // ── Defensive clamping: prevent nonsensical option combinations ──
  const opts: Required<ChunkOptions> = {
    maxChunkSize: Math.max(raw.maxChunkSize, 1),
    minChunkSize: Math.min(raw.minChunkSize, raw.maxChunkSize),
    overlapSize: Math.min(raw.overlapSize, Math.floor(raw.maxChunkSize / 4)),
  };

  // ── Step 1: Recursive split ──
  const rawFragments = recursiveSplit(text.trim(), SEPARATORS, 0, opts);

  // ── Step 2: Merge small chunks ──
  const merged = mergeSmallChunks(rawFragments, opts.minChunkSize);

  // ── Step 3: Add overlap ──
  const withOverlap = addOverlap(merged, opts.overlapSize);

  // ── Step 4: Build final results ──
  return withOverlap.map((content, i) => ({
    content,
    order_index: i,
    char_count: content.length,
    strategy: "recursive" as const,
  }));
}

// ─── Core: Recursive Splitting ──────────────────────────────────────

function recursiveSplit(
  text: string,
  separators: readonly string[],
  level: number,
  opts: Required<ChunkOptions>,
): string[] {
  if (text.length <= opts.maxChunkSize) {
    return [text];
  }

  if (level >= separators.length) {
    return hardSplit(text, opts.maxChunkSize);
  }

  const separator = separators[level];
  const parts = text.split(separator);

  if (parts.length <= 1) {
    return recursiveSplit(text, separators, level + 1, opts);
  }

  const fragments: string[] = [];

  if (isHeaderSeparator(separator)) {
    for (let i = 0; i < parts.length; i++) {
      if (i === 0) {
        if (parts[i].trim().length > 0) fragments.push(parts[i]);
      } else {
        const headerMarker = separator.trimStart();
        const restored = headerMarker + parts[i];
        if (restored.trim().length > 0) fragments.push(restored);
      }
    }
  } else if (separator === ". ") {
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (part.trim().length === 0) continue;

      if (i < parts.length - 1) {
        fragments.push(part + ".");
      } else {
        fragments.push(part);
      }
    }
  } else {
    for (const part of parts) {
      if (part.trim().length > 0) fragments.push(part);
    }
  }

  if (fragments.length <= 1) {
    return recursiveSplit(text, separators, level + 1, opts);
  }

  const result: string[] = [];
  for (const frag of fragments) {
    if (frag.length <= opts.maxChunkSize) {
      result.push(frag);
    } else {
      const subChunks = recursiveSplit(frag, separators, level + 1, opts);
      result.push(...subChunks);
    }
  }

  return result;
}

// ─── Hard Split (Last Resort) ───────────────────────────────────────

function hardSplit(text: string, maxSize: number): string[] {
  const chunks: string[] = [];
  let offset = 0;
  while (offset < text.length) {
    chunks.push(text.slice(offset, offset + maxSize));
    offset += maxSize;
  }
  return chunks;
}

// ─── Merge Small Chunks ─────────────────────────────────────────────

function mergeSmallChunks(chunks: string[], minSize: number): string[] {
  if (chunks.length <= 1) return chunks;

  const result: string[] = [];
  let buffer = "";

  for (const chunk of chunks) {
    if (buffer.length === 0) {
      buffer = chunk;
    } else {
      buffer = buffer + "\n\n" + chunk;
    }

    if (buffer.length >= minSize) {
      result.push(buffer);
      buffer = "";
    }
  }

  if (buffer.length > 0) {
    if (result.length > 0 && buffer.length < minSize) {
      result[result.length - 1] = result[result.length - 1] + "\n\n" + buffer;
    } else {
      result.push(buffer);
    }
  }

  return result;
}

// ─── Overlap ────────────────────────────────────────────────────────

/**
 * Add overlap between consecutive chunks.
 * Exported for reuse by semantic-chunker.ts (D39).
 */
export function addOverlap(chunks: string[], overlapSize: number): string[] {
  if (chunks.length <= 1 || overlapSize <= 0) return chunks;

  const result: string[] = [chunks[0]];

  for (let i = 1; i < chunks.length; i++) {
    const prevChunk = chunks[i - 1];

    let overlapStart = Math.max(0, prevChunk.length - overlapSize);

    if (overlapStart > 0) {
      const spaceIdx = prevChunk.indexOf(" ", overlapStart);
      if (spaceIdx !== -1 && spaceIdx < prevChunk.length) {
        overlapStart = spaceIdx + 1;
      }
    }

    const overlapText = prevChunk.slice(overlapStart).trim();

    if (overlapText.length > 0) {
      result.push(overlapText + "\n...\n" + chunks[i]);
    } else {
      result.push(chunks[i]);
    }
  }

  return result;
}

// ─── Strategy Selection (D41, D42) ──────────────────────────────────

/**
 * Recommend a chunking strategy based on text characteristics.
 *
 * @param text            The text to be chunked
 * @param forceStrategy   Optional override — skips heuristic
 * @param thresholdChars  Optional char threshold for semantic upgrade (default: 4000)
 * @returns               The recommended strategy
 */
export function selectChunkStrategy(
  text: string,
  forceStrategy?: "recursive" | "semantic",
  thresholdChars?: number,
): "recursive" | "semantic" {
  if (forceStrategy === "recursive" || forceStrategy === "semantic") {
    return forceStrategy;
  }

  if (!text || text.trim().length === 0) return "recursive";

  const SEMANTIC_THRESHOLD_CHARS = thresholdChars ?? 4000;

  if (text.trim().length >= SEMANTIC_THRESHOLD_CHARS) {
    return "semantic";
  }

  return "recursive";
}
